(function(){
'use strict';
var KEY='yu-xiao-miao-v2',OLD='yu-xiao-miao-v1',today=dateText(new Date());
var state={day:today,view:'today',period:'day',status:'全部',modal:null};
var EMPTY={settings:{storeName:'于小喵宠物店',monthlyBudget:8000},staff:['小喵','于于'],tasks:[],appointments:[],flows:[]};
var db=load();
function $(id){return document.getElementById(id)}
function copy(x){return JSON.parse(JSON.stringify(x))}
function dateText(x){var d=new Date(x);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function money(x){return '¥'+Number(x||0).toLocaleString('zh-CN',{maximumFractionDigits:2})}
function sum(a){return a.reduce(function(s,x){return s+Number(x.amount||0)},0)}
function html(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function load(){try{var raw=localStorage.getItem(KEY)||localStorage.getItem(OLD),x=raw?JSON.parse(raw):copy(EMPTY);x.settings=x.settings||copy(EMPTY.settings);x.staff=Array.isArray(x.staff)&&x.staff.length?x.staff:copy(EMPTY.staff);x.tasks=Array.isArray(x.tasks)?x.tasks:[];x.appointments=Array.isArray(x.appointments)?x.appointments:[];x.flows=Array.isArray(x.flows)?x.flows:[];return x}catch(e){console.error('Data load failed',e);return copy(EMPTY)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function status(o){if(o.status==='已取消')return'已取消';return new Date(o.date+'T'+(o.time||'23:59')+':00').getTime()<Date.now()?'已服务':'待服务'}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(function(){$('toast').classList.remove('show')},1800)}
function closeModal(){$('modal').classList.add('hidden');state.modal=null}
function setView(v){if(!$(v+'View'))return;state.view=v;document.querySelectorAll('.view').forEach(function(x){x.classList.toggle('active',x.id===v+'View')});document.querySelectorAll('nav [data-view]').forEach(function(x){x.classList.toggle('active',x.dataset.view===v)});$('pageTitle').textContent={today:'今日经营',appointments:'预约管理',operations:'经营分析',settings:'门店设置'}[v];$('voiceFab').classList.toggle('hidden',v==='settings');render();window.scrollTo(0,0)}
function render(){if(state.view==='today')renderToday();if(state.view==='appointments')renderOrders();if(state.view==='operations')renderOperations();if(state.view==='settings')renderSettings()}
function taskRow(t){return'<div class="task '+(t.done?'done ':'')+(t.cancelled?'cancelled':'')+'"><div class="task-left"><button class="check" data-action="toggle-task" data-id="'+t.id+'">'+(t.done?'✓':'')+'</button><span class="task-text">'+html(t.text)+'</span></div><span class="task-time">'+html(t.time||'待定')+'</span><div class="order-menu"><button class="more-btn" data-action="menu">⋯</button><div class="menu-pop hidden"><button data-action="edit-task" data-id="'+t.id+'">修改</button><button data-action="cancel-task" data-id="'+t.id+'">'+(t.cancelled?'恢复':'取消')+'</button><button data-action="delete-task" data-id="'+t.id+'">删除</button></div></div></div>'}
function renderToday(){var orders=db.appointments.filter(function(x){return x.date===state.day}),served=orders.filter(function(x){return status(x)==='已服务'}),valid=orders.filter(function(x){return status(x)!=='已取消'}),flows=db.flows.filter(function(x){return x.date===state.day}),d=new Date(state.day+'T12:00:00');$('today').textContent=d.getFullYear()+'年'+(d.getMonth()+1)+'月'+d.getDate()+'日';$('weekday').textContent='星期'+['日','一','二','三','四','五','六'][d.getDay()];$('appointmentCount').textContent=orders.length+' 个预约';$('doneCount').textContent=served.length;$('pendingCount').textContent=orders.filter(function(x){return status(x)==='待服务'}).length;$('todayRevenue').textContent=money(sum(valid));$('netRevenue').textContent=money(sum(flows.filter(function(x){return x.type==='income'}))-sum(flows.filter(function(x){return x.type==='expense'})));var tasks=db.tasks.filter(function(x){return x.date===state.day}).map(taskRow);$('tasks').innerHTML=tasks.join('')||'<p class="empty">所选日期暂无安排</p>'}
function bounds(anchor){var d=new Date(anchor+'T12:00:00'),s=new Date(d),e=new Date(d);if(state.period==='week'){var w=d.getDay()||7;s.setDate(d.getDate()-w+1);e=new Date(s);e.setDate(s.getDate()+6)}if(state.period==='month'){s.setDate(1);e.setMonth(e.getMonth()+1,0)}if(state.period==='quarter'){s.setMonth(Math.floor(d.getMonth()/3)*3,1);e=new Date(s);e.setMonth(s.getMonth()+3,0)}if(state.period==='year'){s.setMonth(0,1);e.setMonth(11,31)}return[dateText(s),dateText(e)]}
function orderRow(o){var st=status(o);return'<article class="appointment-card"><div class="appointment-head"><time>'+html(o.date+' '+o.time)+'</time><span class="badge '+(st==='已取消'?'cancelled':'')+'">'+st+'</span><div class="order-menu"><button class="more-btn" data-action="menu">⋯</button><div class="menu-pop hidden"><button data-action="edit-order" data-id="'+o.id+'">改约</button><button data-action="'+(st==='已取消'?'restore-order':'cancel-order')+'" data-id="'+o.id+'">'+(st==='已取消'?'恢复预约':'取消订单')+'</button></div></div></div><div class="appointment-body"><div><b>'+html(o.pet)+' · '+html(o.owner||'未填写')+'</b><div class="appointment-meta">'+html(o.service)+' · '+html(o.staff)+(o.phone?' · '+html(o.phone):'')+'</div></div><strong>'+money(o.amount)+'</strong></div></article>'}
function renderOrders(){var range=bounds($('appointmentDate').value||state.day),list=db.appointments.filter(function(x){return x.date>=range[0]&&x.date<=range[1]});if(state.status!=='全部')list=list.filter(function(x){return status(x)===state.status});list.sort(function(a,b){return(b.date+b.time).localeCompare(a.date+a.time)});var done=list.filter(function(x){return status(x)==='已服务'});$('filterCount').textContent=list.length;$('filterRevenue').textContent=money(sum(list.filter(function(x){return status(x)!=='已取消'})));$('filterCompletion').textContent=(list.length?Math.round(done.length/list.length*100):0)+'%';$('appointmentList').innerHTML=list.map(orderRow).join('')||'<div class="empty">当前条件下没有订单</div>'}
function renderOperations(){var month=$('operationMonth').value||state.day.slice(0,7),flows=db.flows.filter(function(x){return x.date.indexOf(month)===0}),inc=sum(flows.filter(function(x){return x.type==='income'})),exp=sum(flows.filter(function(x){return x.type==='expense'})),jobs=db.appointments.filter(function(x){return x.date.indexOf(month)===0&&status(x)==='已服务'});$('monthIncome').textContent=money(inc);$('monthExpense').textContent=money(exp);$('monthNet').textContent=money(inc-exp);$('avgTicket').textContent=money(jobs.length?sum(jobs)/jobs.length:0);var days=Array.from({length:7},function(_,i){var d=new Date();d.setDate(d.getDate()-6+i);return dateText(d)}),maximum=Math.max.apply(null,[1].concat(days.map(function(day){return Math.max(sum(flows.filter(function(x){return x.date===day&&x.type==='income'})),sum(flows.filter(function(x){return x.date===day&&x.type==='expense'})))})));$('bars').innerHTML=days.map(function(day){var i=sum(flows.filter(function(x){return x.date===day&&x.type==='income'})),e=sum(flows.filter(function(x){return x.date===day&&x.type==='expense'}));return'<div class="bar-wrap"><i class="bar in" style="height:'+Math.max(2,i/maximum*100)+'%"></i><i class="bar out" style="height:'+Math.max(2,e/maximum*100)+'%"></i><span class="bar-label">'+Number(day.slice(8))+'日</span></div>'}).join('');$('staffPerformance').innerHTML=db.staff.map(function(s){var list=jobs.filter(function(x){return x.staff===s}),revenue=sum(list);return'<div class="staff-row"><i class="staff-avatar">'+html(s[0])+'</i><div><b>'+html(s)+'</b><br><span>'+list.length+' 单 · 客单价 '+money(list.length?revenue/list.length:0)+'</span></div><strong>'+money(revenue)+'</strong></div>'}).join('');$('flowList').innerHTML=flows.sort(function(a,b){return b.date.localeCompare(a.date)}).map(function(x){return'<div class="record flow '+x.type+'"><div class="record-icon">'+(x.type==='income'?'↗':'↘')+'</div><div class="record-main"><b>'+html(x.note)+'</b><span>'+html(x.date+' · '+x.cat+(x.staff?' · '+x.staff:''))+'</span></div><strong class="record-amount">'+(x.type==='income'?'+':'-')+money(x.amount)+'</strong></div>'}).join('')||'<p class="empty">本月暂无收支流水</p>'}
function renderSettings(){$('storeName').value=db.settings.storeName;$('monthlyBudget').value=db.settings.monthlyBudget;$('staffSettings').innerHTML=db.staff.map(function(s,i){return'<div class="staff-setting"><span>'+html(s)+'</span>'+(db.staff.length>1?'<button data-action="remove-staff" data-id="'+i+'">移除</button>':'')+'</div>'}).join('')}
function show(title,body,mode,id){state.modal={mode:mode,id:id||null};$('modalTitle').textContent=title;$('form').innerHTML=body;$('modal').classList.remove('hidden')}
function options(selected){return db.staff.map(function(s){return'<option '+(s===selected?'selected':'')+'>'+html(s)+'</option>'}).join('')}
function taskForm(x){return'<div class="field"><label>事项<input id="ftext" value="'+html(x.text||'')+'"></label></div><div class="field"><label>日期<input id="fdate" type="date" value="'+x.date+'"></label></div><div class="field"><label>时间<input id="ftime" type="time" value="'+x.time+'"></label></div><button class="save" data-action="save-modal">保存安排</button>'}
function orderForm(x,record){return'<div class="field"><label>日期<input id="fdate" type="date" value="'+x.date+'"></label></div><div class="field"><label>时间<input id="ftime" type="time" value="'+x.time+'"></label></div><div class="field"><label>宠物姓名<input id="fpet" value="'+html(x.pet||'')+'"></label></div><div class="field"><label>主人称呼<input id="fowner" value="'+html(x.owner||'')+'"></label></div><div class="field"><label>主人电话<input id="fphone" type="tel" value="'+html(x.phone||'')+'"></label></div><div class="field"><label>预约项目<input id="fservice" value="'+html(x.service||'基础洗护')+'"></label></div><div class="field"><label>员工<select id="fstaff">'+options(x.staff)+'</select></label></div><div class="field"><label>金额<input id="famount" type="number" value="'+(x.amount||'')+'"></label></div>'+(record?'<div class="field"><label>收款方式<select id="fpayment"><option>微信</option><option>抖音</option><option>美团</option><option>现金</option><option>支付宝</option><option>其他</option></select></label></div><div class="field"><label>语音内容<div class="voice-note"><input id="fnote" placeholder="可选"><button type="button" class="voice" data-action="voice">●</button></div></label></div><p class="hint" id="voiceHint">点击圆点开始语音录入</p>':'')+'<button class="save" data-action="save-modal">保存</button>'}
function flowForm(type){return'<div class="field"><label>日期<input id="fdate" type="date" value="'+state.day+'"></label></div><div class="field"><label>金额<input id="famount" type="number"></label></div><div class="field"><label>分类<input id="fcat" value="'+(type==='income'?'服务收入':'耗材采购')+'"></label></div><div class="field"><label>备注<input id="fnote"></label></div><button class="save" data-action="save-modal">保存</button>'}
function open(type){if(type==='task')return show('添加今日安排',taskForm({date:state.day,time:'09:00'}),'task');if(type==='appointment')return show('新建预约',orderForm({date:$('appointmentDate').value||state.day,time:'10:00',staff:db.staff[0]}),'appointment');if(type==='record')return show('手动记录一笔',orderForm({date:state.day,time:new Date().toTimeString().slice(0,5),staff:db.staff[0]},true),'record');if(type==='staff')return show('添加员工','<div class="field"><label>员工姓名<input id="fstaffname"></label></div><button class="save" data-action="save-modal">添加</button>','staff');show(type==='income'?'记一笔收入':'记一笔支出',flowForm(type),type)}
function saveModal(){var m=state.modal;if(!m)return;if(m.mode==='task'||m.mode==='edit-task'){var text=$('ftext').value.trim();if(!text)return toast('请填写事项');var t=m.id?db.tasks.find(function(x){return x.id===m.id}):null;if(t){t.text=text;t.date=$('fdate').value;t.time=$('ftime').value}else db.tasks.push({id:Date.now(),text:text,date:$('fdate').value,time:$('ftime').value,done:false})}else if(m.mode==='appointment'||m.mode==='record'||m.mode==='edit-order'){var pet=$('fpet').value.trim(),amount=Number($('famount').value);if(!pet||!amount)return toast('请填写宠物姓名和金额');var o=m.id?db.appointments.find(function(x){return x.id===m.id}):null,v={date:$('fdate').value,time:$('ftime').value,pet:pet,owner:$('fowner').value.trim(),phone:$('fphone').value.trim(),service:$('fservice').value.trim(),staff:$('fstaff').value,amount:amount};if(o)Object.assign(o,v);else db.appointments.push(Object.assign({id:Date.now(),payment:$('fpayment')?$('fpayment').value:''},v))}else if(m.mode==='staff'){var name=$('fstaffname').value.trim();if(!name||db.staff.indexOf(name)>=0)return toast('请输入新的员工姓名');db.staff.push(name)}else{var amount2=Number($('famount').value);if(!amount2)return toast('请填写金额');db.flows.push({id:Date.now(),date:$('fdate').value,type:m.mode,amount:amount2,cat:$('fcat').value.trim(),note:$('fnote').value.trim()||$('fcat').value.trim()})}save();closeModal();render();toast('已保存')}
function exportCsv(){var rows=['日期,类型,分类,备注,金额,员工'].concat(db.flows.map(function(x){return[x.date,x.type==='income'?'收入':'支出',x.cat,x.note,x.amount,x.staff||''].map(function(v){return'"'+String(v).replace(/"/g,'""')+'"'}).join(',')})),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv'}));a.download='于小喵经营流水.csv';a.click()}
function action(e){var node=e.target.closest('[data-action]');if(!node){document.querySelectorAll('.menu-pop').forEach(function(x){x.classList.add('hidden')});return}var a=node.dataset.action,id=Number(node.dataset.id);if(a==='menu'){e.stopPropagation();var menu=node.nextElementSibling;document.querySelectorAll('.menu-pop').forEach(function(x){if(x!==menu)x.classList.add('hidden')});return menu.classList.toggle('hidden')}if(a==='save-modal')return saveModal();if(a==='edit-task'){var t=db.tasks.find(function(x){return x.id===id});if(t)show('修改工作安排',taskForm(t),'edit-task',id);return}if(a==='edit-order'){var o=db.appointments.find(function(x){return x.id===id});if(o)show('修改预约',orderForm(o),'edit-order',id);return}if(a==='toggle-task'){var t1=db.tasks.find(function(x){return x.id===id});if(t1)t1.done=!t1.done}if(a==='cancel-task'){var t2=db.tasks.find(function(x){return x.id===id});if(t2)t2.cancelled=!t2.cancelled}if(a==='delete-task'){if(!confirm('删除这条工作安排？'))return;db.tasks=db.tasks.filter(function(x){return x.id!==id})}if(a==='cancel-order'){var o1=db.appointments.find(function(x){return x.id===id});if(o1)o1.status='已取消'}if(a==='restore-order'){var o2=db.appointments.find(function(x){return x.id===id});if(o2)delete o2.status}if(a==='remove-staff')db.staff.splice(id,1);save();render()}
document.addEventListener('click',function(e){var v=e.target.closest('[data-view]');if(v){setView(v.dataset.view);return}var op=e.target.closest('[data-open]');if(op){e.preventDefault();open(op.dataset.open);return}if(e.target.closest('#close')||e.target.id==='modal'){closeModal();return}var st=e.target.closest('#statusFilter [data-status]');if(st){state.status=st.dataset.status==='已完成'?'已服务':st.dataset.status;document.querySelectorAll('#statusFilter button').forEach(function(x){x.classList.toggle('active',x===st)});renderOrders();return}var p=e.target.closest('[data-period]');if(p){state.period=p.dataset.period;document.querySelectorAll('[data-period]').forEach(function(x){x.classList.toggle('active',x===p)});renderOrders();return}if(e.target.closest('#prev,#next')){var d=new Date(state.day+'T12:00:00');d.setDate(d.getDate()+(e.target.closest('#next')?1:-1));state.day=dateText(d);renderToday();return}if(e.target.closest('#export,#settingsExport'))return exportCsv();if(e.target.closest('#addStaff'))return open('staff');if(e.target.closest('#saveSettings')){db.settings.storeName=$('storeName').value.trim()||'于小喵宠物店';db.settings.monthlyBudget=Number($('monthlyBudget').value)||0;save();toast('门店设置已保存');return}if(e.target.closest('#clearData')&&confirm('确定清空当前设备的全部经营数据吗？此操作无法撤销。')){db=copy(EMPTY);save();render();toast('本机数据已重置');return}action(e)});
document.addEventListener('change',function(e){if(e.target.id==='appointmentDate')renderOrders();if(e.target.id==='operationMonth')renderOperations()});
window.addEventListener('error',function(e){console.error('Application error',e.error||e.message)});
document.addEventListener('click',function(e){if(!e.target.closest('[data-action="voice"]'))return;e.preventDefault();e.stopImmediatePropagation();var R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){$('voiceHint').textContent='当前手机浏览器暂不支持语音识别';return}var r=new R();r.lang='zh-CN';r.onstart=function(){$('voiceHint').textContent='正在听，请说记账内容'};r.onresult=function(result){$('fnote').value=result.results[0][0].transcript;$('voiceHint').textContent='识别完成，请核对内容'};r.onerror=function(){$('voiceHint').textContent='识别失败，请重试或手动填写'};r.start()},true);
$('appointmentDate').value=state.day;$('operationMonth').value=state.day.slice(0,7);renderToday();
})();
