(function(){
  const KEY='yu-xiao-miao-v2';let period='day',filter='全部';
  const $=id=>document.getElementById(id),db=()=>JSON.parse(localStorage.getItem(KEY)||'{}'),save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const stamp=(d,t)=>new Date(`${d}T${t||'23:59'}:00`),statusOf=o=>o.status==='已取消'?'已取消':stamp(o.date,o.time)<new Date()?'已服务':'待服务';
  function bounds(anchor){const d=new Date(anchor+'T12:00:00'),s=new Date(d),e=new Date(d);if(period==='week'){const w=d.getDay()||7;s.setDate(d.getDate()-w+1);e.setDate(s.getDate()+6)}if(period==='month'){s.setDate(1);e.setMonth(s.getMonth()+1,0)}if(period==='quarter'){s.setMonth(Math.floor(d.getMonth()/3)*3,1);e.setMonth(s.getMonth()+3,0);e.setDate(0)}if(period==='year'){s.setMonth(0,1);e.setMonth(11,31)}return[s.toISOString().slice(0,10),e.toISOString().slice(0,10)]}
  function actionMenu(o){return `<div class="order-menu"><button class="more-btn" data-menu="${o.id}" aria-label="订单操作">⋯</button><div class="menu-pop hidden" id="menu-${o.id}"><button data-edit="${o.id}">改约</button>${statusOf(o)==='已取消'?`<button data-restore="${o.id}">恢复预约</button>`:`<button data-cancel="${o.id}">取消订单</button>`}</div></div>`}
  function render(){document.querySelectorAll('.orders-note').forEach(x=>x.remove());const data=db(),anchor=$('appointmentDate').value||new Date().toISOString().slice(0,10),[from,to]=bounds(anchor);let list=(data.appointments||[]).filter(o=>o.date>=from&&o.date<=to).map(o=>({...o,computedStatus:statusOf(o)}));if(filter!=='全部')list=list.filter(o=>o.computedStatus===filter);const done=list.filter(o=>o.computedStatus==='已服务'),cancel=list.filter(o=>o.computedStatus==='已取消'),valid=list.filter(o=>o.computedStatus!=='已取消');$('filterCount').textContent=list.length;$('filterRevenue').textContent='¥'+valid.reduce((s,o)=>s+Number(o.amount||0),0).toLocaleString('zh-CN');$('filterCompletion').textContent=(list.length?Math.round(done.length/list.length*100):0)+'%';$('appointmentList').innerHTML=list.sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).map(o=>`<article class="appointment-card"><div class="appointment-head"><time>${o.date} ${o.time}</time><span class="badge ${o.computedStatus==='已取消'?'cancelled':''}">${o.computedStatus}</span>${actionMenu(o)}</div><div class="appointment-body"><div><b>${o.pet} · ${o.owner||'未填写'}</b><div class="appointment-meta">${o.service} · ${o.staff}${o.phone?' · '+o.phone:''}</div></div><strong>¥${Number(o.amount||0).toLocaleString('zh-CN')}</strong></div></article>`).join('')||'<div class="empty">当前条件下没有订单</div>';$('appointmentList').insertAdjacentHTML('beforebegin',`<p class="orders-note">${from===to?from:from+' 至 '+to}<span class="order-count">共 ${list.length} 单 · 已服务 ${done.length} 单 · 已取消 ${cancel.length} 单</span></p>`)}
  function edit(id){const data=db(),o=data.appointments.find(x=>x.id===id);if(!o)return;$('modalTitle').textContent='修改预约';$('modal').classList.remove('hidden');$('form').innerHTML=`<div class="order-origin">当前：${o.date} ${o.time}</div><div class="field"><label>日期<input id="edate" type="date" value="${o.date}"></label></div><div class="field"><label>时间<input id="etime" type="time" value="${o.time}"></label></div><div class="field"><label>项目<input id="eservice" value="${o.service}"></label></div><button class="save" id="esave">保存修改</button>`;$('esave').onclick=()=>{o.date=$('edate').value;o.time=$('etime').value;o.service=$('eservice').value;save(data);$('modal').classList.add('hidden');render()}}
  function cancel(id){const reason=prompt('请输入取消原因');if(reason===null)return;const data=db(),o=data.appointments.find(x=>x.id===id);if(o){o.status='已取消';o.cancelReason=reason||'未填写';save(data);render()}}
  function restore(id){const data=db(),o=data.appointments.find(x=>x.id===id);if(o){delete o.status;delete o.cancelReason;save(data);render()}}
  document.addEventListener('click',e=>{const menu=e.target.closest('[data-menu]'),editBtn=e.target.closest('[data-edit]'),cancelBtn=e.target.closest('[data-cancel]'),restoreBtn=e.target.closest('[data-restore]');document.querySelectorAll('.menu-pop').forEach(x=>{if(!menu||x.id!==`menu-${menu.dataset.menu}`)x.classList.add('hidden')});if(menu){$('menu-'+menu.dataset.menu).classList.toggle('hidden');return}if(editBtn)edit(Number(editBtn.dataset.edit));if(cancelBtn)cancel(Number(cancelBtn.dataset.cancel));if(restoreBtn)restore(Number(restoreBtn.dataset.restore))});
  document.querySelectorAll('#statusFilter [data-status]').forEach(b=>b.onclick=()=>{filter=b.dataset.status==='已完成'?'已服务':b.dataset.status;document.querySelectorAll('#statusFilter [data-status]').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));render()});$('appointmentDate').onchange=render;window.addEventListener('orders:refresh',render);setTimeout(render,80);
})();
